config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :users, only: [:show]
  resources :accountants, only: [:index, :show] do
    post '/send_email', to: 'accountants#send_email'
  end
  resources :enquiries, only: [:new, :create, :show, :destroy, :update, :edit]
  resources :quotes, only: [:new, :create, :destroy] do
    get 'change_status'
    collection do
      get 'new_admin'
      post 'id_check'
    end
  end
  namespace :api, defaults: { format: :json } do
      namespace :v1 do
        get 'enquiries/:id', to: 'enquiries#show_quotes'
      end
    end
  get 'network', to: 'users#network'
end

app/models/quote.rb
class Quote < ApplicationRecord
  after_create :send_quote_create_email

  belongs_to :enquiry
  belongs_to :accountant
  validates :message, presence: true
  validates :invite, inclusion: { in: [true, false] }

  def send_quote_create_email
    QuoteMailer.created(self).deliver_now
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def new
    @accountant = Accountant.find(params[:accountant][:accountant_id])
    @enquiry = Enquiry.find(params[:accountant][:id])
    @quote = Quote.new(enquiry: @enquiry)
    authorize @quote
  end

  def new_admin
    authorize current_user
    @quote = Quote.new
  end

  def id_check
    authorize current_user
    @accountant = Accountant.where(id: params[:quote][:accountant_id]).first
    @enquiry = Enquiry.where(id: params[:quote][:enquiry_id]).first
    respond_to do |format|
      format.js # <-- will render `app/views/quotes/id_check.js.erb`
    end
  end

  def create
    @quote = Quote.new(quote_params)
    if @quote.save
      redirect_to user_path(@quote.enquiry.user)
    else
      render :new
    end
    authorize @quote
  end

  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    authorize @quote
  end

  def change_status
    @quote = Quote.find(params[:quote_id])
    @quote.successful = true
    authorize @quote
    unless @quote.save
      render :show
    end
  end

  private

  def quote_params
    params.require(:quote).permit(:message, :accountant_id, :enquiry_id, :invite, :successful)
  end
end

app/views/quotes/_accountant_id_check.html.erb
<% if @accountant %>
  <span id="accountant-id-text"><%= @accountant.name %></span>
<% else %>
  <span id="accountant-id-text">NOT FOUND</span>
<% end %>

app/views/quotes/_enquiry_id_check.html.erb
<% if @enquiry %>
  <span id="enquiry-id-text"><%= @enquiry.title %></span>
<% else %>
  <span id="enquiry-id-text">NOT FOUND</span>
<% end %>

app/views/quotes/_new_form.html.erb
<%= simple_form_for quote do |f| %>
  <%= f.input :accountant_id, as: :hidden, input_html: { value: accountant.id } %>
  <%= f.input :enquiry_id, as: :hidden, input_html: { value: enquiry.id } %>
  <%= f.input :invite, as: :hidden, input_html: { value: true } %>
  <%= f.input :successful, as: :hidden, input_html: { value: true } %>
  <%= f.input :message, label: false %>
  <%= f.submit "Invite", class:'btn btn-primary btn-block', id: 'invite-button' %>
<% end %>

app/views/quotes/change_status.js.erb
document.querySelector('#close<%= @quote.id %>').click()
document.querySelector("[data-connect-id='<%= @quote.id %>']").remove();
p = document.querySelector("#connect<%= @quote.id %>")
p.innerHTML = "<strong>Connected</strong>";
p.parentElement.setAttribute("id", "connected-pill");

app/views/quotes/destroy.js.erb
document.querySelector("[data-quote-id='<%= @quote.id %>']")
  .remove();

app/views/quotes/id_check.js.erb
var accountantCheckInput = document.getElementById('quote_accountant_id');
var accountantText = document.getElementById('accountant-id-text');
var renderResult = `<%= j render "quotes/accountant_id_check" %>`;

if (accountantText) {
  accountantText.innerHTML = "";
}
accountantCheckInput.insertAdjacentHTML('afterend', renderResult );

var enquiryCheckInput = document.getElementById('quote_enquiry_id');
var enquiryText = document.getElementById('enquiry-id-text');
var renderResult = `<%= j render "quotes/enquiry_id_check" %>`;

if (enquiryText) {
  enquiryText.innerHTML = "";
}
enquiryCheckInput.insertAdjacentHTML('afterend', renderResult );

app/views/quotes/new.html.erb
<div class="grey-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6 col-md-offset-3">
        <div class="white-card">
          <h2>Invite <%= @accountant.name %> to quote</h2>
          <hr>
          <h4>Leave a message regarding <strong><%= @enquiry.title %>:</strong></h4>
          <%= render 'new_form', accountant: @accountant, enquiry: @enquiry, quote: @quote %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quotes/new_admin.html.erb
<div class="grey-wrapper">
  <div class="container">
    <div class="white-card">
      <h1>Admin page: create quote</h1>
      <h2>On behalf of accountant</h2>
      <hr>
      <%= simple_form_for @quote do |f| %>
        <%= f.input :accountant_id, label: "Accountant Id" %>
        <%= f.input :enquiry_id, label: "Enquiry Id" %>
        <%= f.input :message %>
        <%= f.input :invite, as: :hidden, input_html: { value: false } %>
        <%= f.submit "Create quote", class:'btn btn-primary btn-block' %>
      <% end %>
      <hr>
      <h3>Check IDs Here</h3>
      <%= simple_form_for @quote, remote: true, url: id_check_quotes_path do |f| %>
        <%= f.input :accountant_id, label: 'Accountant ID', html: { id: :Accountant_check } %>
        <%= f.input :enquiry_id, label: 'Enquiry ID', html: { id: :Accountant_check } %>
        <%= f.submit "Check Accountant ID" %>
      <% end %>
    </div>
  </div>
</div>