config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :users, only: [:show]
  resources :accountants, only: [:index, :show] do
    post '/send_email', to: 'accountants#send_email'
  end
  resources :enquiries, only: [:new, :create, :show, :destroy, :update, :edit]
  resources :quotes, only: [:new, :create, :destroy] do
    get 'change_status'
    collection do
      get 'new_admin'
      post 'id_check'
    end
  end
  namespace :api, defaults: { format: :json } do
      namespace :v1 do
        get 'enquiries/:id', to: 'enquiries#show_quotes'
      end
    end
  get 'network', to: 'users#network'
end

app/models/user.rb
class User < ApplicationRecord
  after_create :attach_enquiries, :send_user_create_email

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :enquiries, dependent: :destroy
  validates :name, presence: true
  validates :email, format: { with: /[^@]{1,}\@[^@.]{1,}\.[^@]{1,}/ }, uniqueness: true
  validates :company_size, inclusion: { in: COMPANY_SIZES }, allow_nil: true
  validates :company_industry, inclusion: { in: INDUSTRIES }, allow_nil: true

  private

  def attach_enquiries
    Enquiry.where(email: email, user_id: nil).each do |enquiry|
      enquiry.update(user: self)
    end
  end

  def send_user_create_email
    UserMailer.created(self).deliver_now
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    flash[:to_dashboard] = true if params[:email]
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    flash[:to_dashboard] = true if params[:email]
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :network

  def show
    @user = User.find(params[:id])
    @user_enquiries = Enquiry.where(user_id: @user.id)
    authorize @user
  end

  def network
    @user = current_user
    if @user
      authorize @user
    else
      authorize User.first
    end
  end
end

app/views/users/_fillQuotes.html.erb
<script>
  quotesContainer<%= index + 1 %> = document.getElementById('quotes-container-<%= index + 1 %>');

  function refresh() {
    fetch('/api/v1/enquiries/<%= enquiry.id %>')
    .then((results) => results.json())
    .then((data) => {
      quotesContainer<%= index + 1 %>.innerHTML = '';
      if (data.quotes.length === 0) {
        text = `<div class="row text-center">\
                  <div class="col-sm-12 col-md-6 col-md-offset-3">\
                    <h3>No connections yet. We are finding the best fit accountants for your business</h3>\
                    <p>Need for speed? <a href="/accountants">Invite accountants</a> to your enquiry now.</p>\
                  </div>\
                </div>`
                quotesContainer<%= index + 1 %>.insertAdjacentHTML('afterbegin', text)
      } else {
        data.quotes.forEach((quote) => {
          if (quote.invite === true) {
            var invited = '<div class="pill" id="invited-you">\
                            <p><strong>Invited by You</strong></p>\
                          </div>'
          } else {
            var invited = '<div class="pill" id="invited-new">\
                            <p><strong>New Quote</strong></p>\
                          </div>'
          }
          if (quote.successful === true) {
            var successful = `<div class="pill" id="connected-pill">\
                                <p class ="connect"><strong>Connected</strong> </p>\
                              </div>`
          } else {
            var successful = `<div class="pill" id="unconnected-pill">\
                                <p id="connect${quote.id}"><strong>Not connected</strong> </p>\
                              </div>`
          }
          acctName = `<a href="/accountants/${quote.accountant.id}">${quote.accountant.name}</a>`
          acctEmail = `${quote.accountant.email}`
          if (quote.invite == true) {
            acctMsg = `You wrote: ${quote.message}`
          } else {
            acctMsg = `They wrote: ${quote.message}`
          }
          var buttons = `<a data-confirm="Are you sure?" class="btn btn-info btn" rel="nofollow"\
                            data-method="delete" href="/quotes/${quote.id}" data-remote="true">Discard</a>`;
          var emailButton;

          if (quote.successful != true) {
            var buttons = `<button type="button" class="btn btn-primary" id="connect-button" data-toggle="modal"\
                      data-target="#id-${quote.id}" data-connect-id='${quote.id}'>\
                        Connect\
                      </button>\
                      <a data-confirm="Are you sure?" class="btn btn-info btn" id="discard-button" rel="nofollow"\
                      data-method="delete" href="/quotes/${quote.id}" data-remote="true">Discard</a>
                      <div class="modal fade" id="id-${quote.id}" tabindex="-1"\
                      role="dialog" aria-labelledby="myModalLabel">\
                        <div class="modal-dialog" role="document">\
                          <div class="modal-content">\
                            <div class="modal-header">\
                              <button type="button" class="close" id="close${quote.id}" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>\
                              <h4 class="modal-title" id="myModalLabel">Connect with ${quote.accountant.name}</h4>\
                            </div>\
                            <div class="modal-body">\
                              <p>Connect to <strong>share your contact details</strong> with ${quote.accountant.name}.<br><br>That's it! <strong>They'll reach out</strong> so you can get back to the work you'd rather be doing.</p>\
                              <form action="/accountants/${quote.accountant.id}/send_email" class="hidden" method="post" id="email-form${quote.id}">\
                                <hr>\
                                <p>From: <%= current_user.email %></p>\
                                <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>\
                                <input type="text" placeholder="Subject" id='email-subject' name="subject">\
                                <textarea placeholder="Your message" id='email-body' name="body" rows="6"></textarea>\
                                <button class="btn btn-primary" data-remote="true" id="send-now${quote.id}">Send</button>\
                              </form>\
                            </div>\
                            <div class="modal-footer">\
                              <div class="footer-flex">\
                                <p class="no-margin"><strong>Need for speed?</strong> Feel free to <strong><a\ id="send-email${quote.id}" href='#' data-remote="true">Reach out now.</a></strong></p>\
                                <a class="btn btn-primary" data-remote="true" href="/quotes/${quote.id}/change_status">Connect</a>\
                              </div>\
                            </div>\
                          </div>\
                        </div>\
                      </div>`;
          }
          text = `<div class="col-xs-12 col-sm-4 slow-appear" data-quote-id='${quote.id}'>\
                    <div class="quote-card">\
                      <div class="acct-card-services" id="quote-pills">\
                        ${invited}\
                        ${successful}
                      </div>\
                      <h4 id="quote-title">${acctName}</h4>\
                      <p id="quote-email">${acctEmail}</p>\
                      <p id="quote-message">${acctMsg}</p>\
                      <div id="quote-buttons">${buttons}</div>\
                    </div>\
                  </div>`;
          quotesContainer<%= index + 1 %>.insertAdjacentHTML('afterbegin', text)
          var emailButton = document.getElementById(`send-email${quote.id}`);
          var form = document.getElementById(`email-form${quote.id}`);
          var sendNow = document.getElementById(`send-now${quote.id}`);

          if (emailButton) {
            emailButton.addEventListener('click', (event) => {
              console.log(0)
              event.preventDefault();
              form.classList.toggle('hidden');
            });
            sendNow.addEventListener('click', (event) => {
              event.preventDefault();
              Rails.fire(form, 'submit');
            });
          }
        })
      }
      refreshButtons.forEach((button) => button.classList.remove('display-none'));
    });
  };
  document.addEventListener("DOMContentLoaded", refresh());
  discardButtons = document.querySelectorAll('#discard-button');
  discardButtons.forEach((button, index) => {
    button.addEventListener('click', () => document.querySelectorAll('#connect-button').splice(index, 1));
  })

  refreshButtons = document.querySelectorAll('#refresh-button');
  refreshButtons.forEach((button) => {
    button.addEventListener('click', (event) => {
      refresh();
    })
  })
</script>

app/views/users/network.html.erb
<div class="grey-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8 col-md-offset-2">
        <div class="white-card">
          <h2>Accountants trusted in your network</h2>
          <p>
            <strong>Recommendations matter. </strong>Thats why we have the option to see who serves the businesses in your network. <br><br>

            We're fine tuning this feature at the moment, but have no fear, our team of accountant detectives can still help.<br><br>

            Shoot a message over to <a href="mailto:team@accountant-magnet.com">team@accountant-magnet.com</a> to get hands-on help, or just to chat!<br><br>

            Last but certainly not least, We <strong>never share any of your network data</strong> with third parties (including accountants).
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <!-- Nav tabs -->
  <% if @user_enquiries.count > 1 %>
    <ul class="nav nav-tabs" role="tablist">
      <% @user_enquiries.each_with_index do |enquiry, index| %>
        <li role="presentation" class="<%= 'active' if index == 0 %>"><a href="#enquiry-<%= index %>" aria-controls="enquiry-<%= index %>" role="tab" data-toggle="tab"><%= enquiry.title %></a></li>
      <% end %>
    </ul>
  <% else %>
    <ul class="nav nav-tabs hidden" role="tablist">
      <% @user_enquiries.each_with_index do |enquiry, index| %>
        <li role="presentation" class="<%= 'active' if index == 0 %>"><a href="#enquiry-<%= index %>" aria-controls="enquiry-<%= index %>" role="tab" data-toggle="tab"><%= enquiry.title %></a></li>
      <% end %>
    </ul>
  <% end %>

  <!-- Tab panes -->
  <div class="tab-content">
    <% @user_enquiries.each_with_index do |enquiry, index| %>
      <div role="tabpanel" class="tab-pane <%= 'active' if index == 0 %>" id="enquiry-<%= index %>">
        <div class=" grey-wrapper">
          <div class="container">
            <div style="display: flex;">
              <% if current_user.admin %>
                <h3 style="color: red" id="title">Viewing as admin</h3>
              <% end %>
            </div>
            <div class="pos-rel">

              <div class="btm-right">
                <%= link_to "", edit_enquiry_path(enquiry), class:"far fa-edit" %>
                <%= link_to "",  enquiry_path(enquiry), class: "fas fa-trash-alt", method: :delete, data: { confirm: "Are you sure?" } %>
              </div>
              <div class="enquiry-card">
                <div class="display-flex">
                  <h2> <%= enquiry.title %></h2>
                  <div>
                    <%= link_to "Invite Accountants", accountants_path, class:'btn-primary-outline btn btn-sm header-btn'%>
                    <%= link_to "Accountants in my network", network_path, class:'btn-primary btn btn-sm header-btn'%>
                  </div>
                </div>
                <%= enquiry.description %>
                  <div class="acct-card-services">
                    <% enquiry.services.each do |service| %>
                    <div class="card-service">
                      <p><%= service.name %></p>
                    </div>
                    <% end %>
                  </div>
              </div>
            </div>
            <h3>Your Connections <span class="display-none slow-appear btn text-right"></span><i class="fas fa-sync text-center" id="refresh-button"></i></h3>
            <div class="row" id='quotes-container-<%= index + 1 %>'>
              <%= render 'fillQuotes', enquiry: enquiry, index: index %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% if @user_enquiries.count == 0  %>
  <div class="col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4">
    <div class="row text-center">
      <h3> You have no enquiries.</h3>
      <%= link_to "New Enquiry", new_enquiry_path, class:'btn-primary-outline btn  header-btn '%>
    </div>
  </div>
<% end %>