config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :users, only: [:show]
  resources :accountants, only: [:index, :show] do
    post '/send_email', to: 'accountants#send_email'
  end
  resources :enquiries, only: [:new, :create, :show, :destroy, :update, :edit]
  resources :quotes, only: [:new, :create, :destroy] do
    get 'change_status'
    collection do
      get 'new_admin'
      post 'id_check'
    end
  end
  namespace :api, defaults: { format: :json } do
      namespace :v1 do
        get 'enquiries/:id', to: 'enquiries#show_quotes'
      end
    end
  get 'network', to: 'users#network'
end

app/models/accountant.rb
class Accountant < ApplicationRecord
  validates :name, presence: true
  # validates :qualification, allow_nil: true, inclusion: { in: QUALIFICATIONS }
  has_many :quotes
  has_many :accountant_services
  has_many :services, through: :accountant_services
  has_many :accountant_industries
  has_many :industries, through: :accountant_industries
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/accountants_controller.rb
class AccountantsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :send_email]
  before_action :find_accountant, only: [:send_email, :show]

  def index
    # Load all accountants
    @accountants = policy_scope(Accountant).paginate(page: params[:page], per_page: 10)

    if params[:accountant]
      # Filter by service
      if params[:accountant][:services].reject(&:blank?).any?
        to_search = params[:accountant][:services].reject(&:blank?).map(&:to_i)
        base_sql = "SELECT id FROM \"accountants\"
                    WHERE EXISTS (SELECT \"accountant_services\".*
                                  FROM \"accountant_services\"
                                  WHERE (accountants.id = accountant_services.accountant_id
                                  AND service_id = #{to_search.first}))"
        to_search[1..-1].each do |id|
          add_serv = " AND EXISTS (SELECT \"accountant_services\".*
                                   FROM \"accountant_services\"
                                   WHERE (accountants.id = accountant_services.accountant_id
                                   AND service_id = #{id}))"
          base_sql += add_serv
        end
        results = Accountant.find_by_sql(base_sql)
        @accountants = @accountants.where(id: results.map(&:id)).paginate(page: params[:page], per_page: 10)
      end

      # Filter by industry
      if params[:accountant][:industries].reject(&:blank?).any?
        to_search = params[:accountant][:industries].reject(&:blank?).map(&:to_i)
        base_sql = "SELECT id FROM \"accountants\"
                    WHERE EXISTS (SELECT \"accountant_industries\".*
                                  FROM \"accountant_industries\"
                                  WHERE (accountants.id = accountant_industries.accountant_id
                                  AND industry_id = #{to_search.first}))"
        to_search[1..-1].each do |id|
          add_serv = " AND EXISTS (SELECT \"accountant_industries\".*
                                   FROM \"accountant_industries\"
                                   WHERE (accountants.id = accountant_industries.accountant_id
                                   AND industry_id = #{id}))"
          base_sql += add_serv
        end
        results = Accountant.find_by_sql(base_sql)
        @accountants = @accountants.where(id: results.map(&:id)).paginate(page: params[:page], per_page: 10)
      end
    end
    # filter by
    unless params[:search].nil?
      @accountants = @accountants.near(params[:search], 50, order: 'distance') unless params[:search].empty?
    end
  end

  def show
    @show_button = true
    cnt = 0
    if user_signed_in?
      @open_enquiries = current_user.enquiries
      @open_enquiries_no_quote = []
      @open_enquiries.each do |e|
        @open_enquiries_no_quote << e unless e.quotes.any? { |quote| quote.accountant == @accountant }
      end
      current_user.enquiries.each do |enquiry|
        enquiry.quotes.each do |quote|
          if quote.accountant_id == @accountant.id
            cnt += 1
          end
          @show_button = false if cnt == current_user.enquiries.count
        end
      end
    else
      @open_enquiries = []
      @open_enquiries_no_quote = []
    end
  end

  def send_email
    @body = params[:body]
    @email_from = current_user.email
    @subject = params[:subject]
    AccountantMailer.contact(@body, @email_from, @subject, @accountant.email).deliver_now
  end

  private

  def find_accountant
    @accountant = Accountant.find(params[:id] || params[:accountant_id])
    authorize @accountant
  end
end

app/views/accountants/_accountant_card.html.erb
<div class="container">
  <%= link_to accountant_path(accountant), class:'grey-text' do %>
    <div class="white-card border-hover">
      <div class="acct-card-title">
        <div id = "accountant-name">
          <h3><%= accountant.name %></h3>
        </div>
        <div>
          <p>See more details</p>
        </div>
      </div>
      <hr class="sm-margin">
      <div class="acct-card-details">
        <div class="acct-card-contact">
          <% city = accountant.location.split(',')[-3].capitalize %>
          <% post_code = accountant.location.split(',')[-1] %>
          <p class="text-bold"><%= "#{city}, #{post_code}" %></p>
          <p><%= accountant.email %></p>
          <p><%= accountant.phone_number %></p>
        </div>
        <div class="acct-card-services flex-reverse">
          <% accountant.services.first(5).each do |service| %>
            <div class="card-service">
              <p><%= service.name %></p>
            </div>
          <% end %>
        </div>
      </div>
          <div class="service-size">
            <% if accountant.services.size > 5 %>
            <p> +  <%=  accountant.services.size - 5  %> more </p>
            <% end %>
          </div>
    </div>
  <% end %>
</div>

app/views/accountants/_contact_button.html.erb
<% unless @accountant.email.empty? %>
  <a type="button" class="btn btn-info-outline header-btn" data-toggle="modal" data-target="#contactModal">
    Get in touch
  </a>
<% end %>

<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Reach <strong><%= accountant.name %></strong> through one of the following:</h4>
      </div>
      <div class="modal-body">
        <% if @accountant.email %>
          <p>Email: <%= @accountant.email %>
            <% if user_signed_in? %>
              <span style="float: right;">
                <button class="btn btn-primary-outline" id="send-email">Send Email</button>
              </span>
            <% end %>
          </p>
        <% end %>
        <% if @accountant.phone_number %>
          <p>Phone: <%= @accountant.phone_number %></p>
        <% end %>
        <% if @accountant.website %>
          <p>Website: <%= link_to @accountant.website, 'http://' + @accountant.website, target: :_blank %></p>
        <% end %>
        <% if user_signed_in? %>
          <form action="/accountants/<%= @accountant.id %>/send_email" class="hidden" method="post" id="email-form" data-remote="true">
            <hr>
            <p>From: <%= current_user.email %></p>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
            <input type="text" placeholder="Subject" id='email-subject' name="subject">
            <textarea placeholder="Your message" id='email-body' name="body" rows="6"></textarea>
            <button class="btn btn-primary" id="send-now">Send</button>
          </form>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/accountants/_invite_button.html.erb
<% if @show_button %>
  <a type="button" class="btn btn-primary-outline header-btn" data-toggle="modal" data-target="#myModal">
          Invite to enquiry
        </a>
<% end %>

<% if user_signed_in? && @open_enquiries.length > 1 %>

  <% unless @open_enquiries_no_quote.any? %>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><strong><%= accountant.name %></strong> already knows about your enquiries</h4>
          </div>
          <div class="modal-body">
            Pop over to your dashboard to check your enquiries
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= link_to "My dashboard", user_path(current_user), class:'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Which of your enquiries do you want to invite <%= accountant.name %> to? </h4>
            <%= simple_form_for accountant, url: new_quote_path, method: :get do |f| %>
              <%= f.input :accountant_id, as: :hidden, input_html: { value: accountant.id } %>
              <%= f.input :id, as: :radio_buttons, collection: @open_enquiries_no_quote, hint: "Your enquiries that already have connections from this accountant won't show", label: "" %>
              <%= f.submit "Invite to enquiry", class:'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

<% elsif user_signed_in? && @open_enquiries.length == 1 %>

  <% unless @open_enquiries_no_quote.any? %>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel"><strong><%= accountant.name %></strong> already knows about your enquiry <strong><%= @open_enquiries.first.title %></strong></h4>
          </div>
          <div class="modal-body">
            Pop over to your dashboard to check your enquiries
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= link_to "My dashboard", user_path(current_user), class:'btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h2>Invite <%= accountant.name %> to your enquiry</h2>
          </div>
          <div class="modal-body">
            <h4>Leave a message regarding <strong><%=  @open_enquiries.first.title %>:</strong></h4>
            <%= render 'quotes/new_form', accountant: @accountant, enquiry: @open_enquiries.first, quote: Quote.new %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button class='btn btn-primary' id='modal-invite-button'>Invite</button>
          </div>
          <script>
            document.getElementById('invite-button').style.display = 'none';
            const btn = document.getElementById('modal-invite-button');
            btn.addEventListener('click', () => {
              document.getElementById('new_quote').submit();
            });
          </script>
        </div>
      </div>
    </div>
  <% end %>

<% else %>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">You don't have any enquiries yet</h4>
        </div>
        <div class="modal-body">
          Let's quickly make one so you can get the help you need.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= link_to "Let's go!", new_enquiry_path, class:'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/accountants/_no_accountants.html.erb
<h3 style="text-align: center; margin-top: 50px;">Sorry, no accountants match your criteria. Try broadening your search!</h3>

app/views/accountants/index.html.erb
<div class="grey-wrapper">
  <div class="container">
    <div class="display-flex">
      <h1>Find your accountant</h1><%= link_to "Find accountants in my network", network_path, class:'btn btn-info btn-sm', style:'align-self: flex-end; margin-bottom: 22.5px;' %>
    </div>

    <%= simple_form_for Accountant.new, url: accountants_path, method: :get, html: { class: 'accountant-search' } do |f| %>
        <div id="services-field-group">
          <p class="label">Services</p>
          <%= f.input :services, collection: Service.all, label: false, placeholder: 'Search Services', input_html: { class: 'select2-services', multiple: "multiple"} %>
          </div>
        <div id="industries-field-group">
          <p class="label">Industries</p>
          <%= f.input :industries, collection: Industry.all, label: false, input_html: { class: 'select2-industries', multiple: "multiple"} %>
        </div>
        <div id="location-field-group">
          <p class="label">Location</p>
          <%= text_field_tag :search, params[:search] %>
        </div>
      <%= f.button :submit, 'Filter', class: "btn-primary" %>
    <% end %>
  </div>

  <%= render 'no_accountants' if @accountants.length == 0 %>
  <% @accountants.each do |accountant| %>
    <%= render 'accountant_card', accountant: accountant %>
  <% end %>
</div>

<div class="text-center">
  <%= will_paginate @accountants, renderer: BootstrapPagination::Rails %>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
  $(document).ready(function() {
    $(".select2-services").select2({
      placeholder: "Select the services you require:"
    });
     $(".select2-industries").select2({
      placeholder: "Select the industries you require:"
    });
   });
</script>

app/views/accountants/send_email.js.erb
document.getElementById('email-form').innerHTML = "<h4>Your message has been sent!</h4>";

app/views/accountants/show.html.erb
<div class="grey-wrapper">
  <div class="container">
    <div class="white-card display-flex">
      <div>
        <h1><%= @accountant.name %></h1>
        <p><%= @accountant.bio %></p>
      </div>
      <%= render 'invite_button', accountant: @accountant %>
    </div>

    <!-- contact info -->

  <div class="white-card">
    <div class="display-flex">
      <h3>Contact information</h3>
      <%= render 'contact_button', accountant: @accountant %>
    </div>
    <hr class="sm-margin">
    <div class="acct-card-details">
      <div class="acct-card-contact">
        <p><%= @accountant.email %></p>
        <p><%= @accountant.phone_number %></p>
        <p class="text-bold"><%= @accountant.location %></p>
      </div>
      <% if @accountant.website %>
        <%= link_to @accountant.website, 'http://' + @accountant.website, target: :_blank %>
      <% end %>
    </div>
  </div>

    <!-- specialties & Quals -->

  <div class="white-card">
    <h3>Services and qualifications</h3>
    <hr class="sm-margin">
    <div class="display-flex">
      <div class="display-flex">
        <p class="text-bold no-margin">Specializing in:</p>
        <div class="acct-card-services">
          <% @accountant.services.each do |service| %>
            <div class="card-service">
              <p><%= service.name %></p>
            </div>
          <% end %>
        </div>
      </div>
      <div id="qualifications">
        <p class="text-bold no-margin">Qualified by:</p>
        <div id="qual-box">
          <img id="qual-logo" src="https://upload.wikimedia.org/wikipedia/commons/f/f0/ACCA_logo.svg" alt="">
          <p> The Association of Chartered Certified Accountants</p>
        </div>
      </div>
    </div>
    <% if @accountant.industries.any? %>
      <hr class="sm-margin">
      <div>
        <p class="text-bold no-margin">Industries focuses:</p>
        <div id="services">
          <% @accountant.industries.each do |industry| %>
            <div class="industry-service">
              <p><%= industry.name %></p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>